name: portable-release-actions-workflow
on:
  push:
    # # Sequence of patterns matched against refs/tags
    # tags:
    #   - '*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
permissions:
  contents: write
  
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: altium-circuitmaker-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        shell: cmd
        run: |
          curl "https://altium-official-installers.s3.amazonaws.com/CircuitMaker_2.0/CircuitMakerSetup_2.3.0.3.exe?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA3DWNEQM7ZW6YHFNH/20250121/us-east-1/s3/aws4_request&X-Amz-Date=20250121T094159Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Signature=5afee71b904e95959dddf33b6c1148ffeb1a12e1a25699d26b82cf75bec9a57f" -L --output installer.exe &&^
          dir
          
      - name: uncompress msi
        shell: cmd
        run: |
          md installation &&^
          dir &&^
          start "" /wait .\installer.exe -UI:None -InstallAll -AutoInstall -Programs:installation

      # -Documents:"%cd%\installation"

      # - shell: cmd
      #   run: xcopy /H /Y /C "Sculptris.exe.Portable.cmd" "installation"
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "installation"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "installation/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
